### ISSUE TITLE
[Docker] doesn't run anything or seems not working...

### ISSUE THREAD

**Issue by Ramalama2** [scross01/prometheus-klipper-exporter#7]
Hi, basically:

docker run -d -p 9101:9101 -v /server/klipper-exporter/prometheus.yml:/etc/prometheus/prometheus.yml ghcr.io/scross01/prometheus-klipper-exporter:latest

doesn't seem to do the job, im not sure how you are expecting us to mount the yaml inside the container, thats the only thing that i think is a requirement....
however, im not seeing even anything in the conainer running...
i mean the container works, i can exec it etc... just aside from "/root/main" and some system files, there is nothing prometheus or klipper-exporter related inside.

Log:
INFO[0000] Beginning to serve on port :9101             

Thats it.

Maybe you could explain a bit, how the container should run and how you configure "prometheus-klipper-expander" without mapping any config file :-)

Other as that, this project is awesome, i always dreamed to put all the data from klipper into grafana somehow!
Just i would have somehow tryed to find a way to push it into influxdb, instead of prometheus, because of all that time you wait... 15 seconds is pretty long...
grafana ---(scrape 5s)--> prometheus-db ---(scrape 5s)---> prometheus-klipper-exporter ---(scrape 5s)---> moonraker.....
instead of simply sth like:
grafana(influxdb) <--(push)---prometheus-klipper-exporter---(scrape 5s)---> moonraker.....

However, im more as happy that there is at least any solution now!
So thank you very much for that.

Cheers 👍

**Comment by scross01** [comment]
The docker container only contains the klipper-exporter, not a full prometheus installation.  Mounting the prometheus.yml to that container will not have any affect. You need to run prometheus separately. The prometheus.yml config sets how prometheus will poll the exporter.

The container, or the executable, just runs and waits on port :9101 for prometheus to poll it, and then immediately queries klipper (moonraker) and returns the data.  The turn-around for data collection is the 5s prometheus poll (or whatever you set it to). prometheus-klipper-exporter does not have separate polling delay, just additional time for running the query (200ms to 400ms on my system), and grafana will show the latest data from prometheus once it's returned.

e.g.
```
grafana ---(query)--> prometheus:9090 ---(scape 5s)--> klipper-exporter:9101 ---(query)--> moonraker:7125
```

**Comment by scross01** [comment]
Here's an example `docker-compose.yml` I use for testing the exporter.  Runs grafana, prometheus and the klipper-exporter in a single stack.  Change the volume mounts as appropriate

```yaml
version: '2'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    user: 1000:1000
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    expose:
      - 9090
    ports:
      - 9090:9090
    restart: unless-stopped
      
  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://localhost
      GF_SECURITY_ADMIN_PASSWORD: 'password1234!@#$' # change password
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Editor'
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
    ports:
      - "3000:3000/tcp"

  klipper-exporter:
    hostname: klipper-exporter
    image: ghcr.io/scross01/prometheus-klipper-exporter:latest
    container_name: klipper-exporter
    restart: unless-stopped
    expose:
      - 9101
```

To start the stack run:

```
$ docker compose up
...
Attaching to grafana, klipper-exporter, prometheus
...
klipper-exporter  | time="2022-10-13T22:54:06Z" level=info msg="Beginning to serve on port :9101"
prometheus        | ts=2022-10-13T22:54:06.729Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.37.1, branch=HEAD, revision=1ce2197e7f9e95089bfb95cb61762b5a89a8c0da)"
...
grafana           | logger=settings t=2022-10-13T22:54:06.760527825Z level=info msg="Starting Grafana" version=9.1.6 commit=92461d8d1e branch=HEAD compiled=2022-09-20T10:06:14Z
...
klipper-exporter  | time="2022-10-13T22:54:15Z" level=info msg="Starting metrics collection of [process_stats network_stats system_info job_queue directory_info printer_objects] for klipper.home.lan:7125"
klipper-exporter  | time="2022-10-13T22:54:15Z" level=info msg="Collecting process_stats for klipper.home.lan:7125"
klipper-exporter  | time="2022-10-13T22:54:15Z" level=info msg="Collecting directory_info for klipper.home.lan:7125"
klipper-exporter  | time="2022-10-13T22:54:15Z" level=info msg="Collecting job_queue for klipper.home.lan:7125"
klipper-exporter  | time="2022-10-13T22:54:15Z" level=info msg="Collecting system_info for klipper.home.lan:7125"
klipper-exporter  | time="2022-10-13T22:54:15Z" level=info msg="Collecting printer_objects for klipper.home.lan:7125"
...
```
